### ISSUE TITLE
Error filling in template `router_configurer.yml.erb' for `tcp_router_z1/0'

### ISSUE THREAD

**Issue by samdai** [cloudfoundry-incubator/cf-routing-release#15]
When I run command `bosh -n deploy`, there is the following error, I tried final available release and my release, got the same error, how to resolve it?
```
  Started preparing configuration > Binding configuration. Failed: Error filling in template `router_configurer.yml.erb' for `tcp_router_z1/0' (line 4: Can't find property `["router.router_configurer.tcp_router_secret"]') (00:00:00)

Error 100: Error filling in template `router_configurer.yml.erb' for `tcp_router_z1/0' (line 4: Can't find property `["router.router_configurer.tcp_router_secret"]')
```

**Comment by atulkc** [comment]
@samdai looks like your cf deployment manifest doesn't have the required `uaa.clients.tcp_router.secret` property. If you have generated cf-routing deployment manifest using one of our scripts (`bosh-lite/make_manifest`) then it tries to get that property from `cf.yml`, which you specify as first parameter to that script. 

BTW, this (adding new oauth clients) was a recent change that was done in `cf-routing-release` and you will need latest cf release (`develop`/`release_candidate` branch) as well for this to work. So you will face this error if you are working off `develop` branch of cf-routing-release but have an older cf-release. I am little surprised that you are seeing the same error with final release also, can you paste the error that you got while deploying final release? Our final release doesn't have this change yet.

**Comment by samdai** [comment]
Thanks atulkc, you are right , after I change to the latest cf release, this error is gone.
