### ISSUE TITLE
How to configure tcp router?

### ISSUE THREAD

**Issue by samdai** [cloudfoundry-incubator/cf-routing-release#16]
I deployed two applications app1 and app2 to diego, in application app1, I started an activemq server, the port is 61616, in application app2, I create a java client to connect the activemq server in app1, but there is the following error, I can telnet app1.bosh-lite.com:61616 in command console of my lap-top, but can't do it in app2, I also tried the ip address of app1, got the same error
```
message: Could not connect to broker URL: tcp://app1.bosh-lite.com:61616. Reason: java.net.ConnectException: Connection refused
```
I also deployed cf-routing-release to bosh-lite, but didn't work, got the same error. I have two questions here:
(1) I saw cf release has already sub module cf-routing-release,  does cf release support tcp router if I don't git clone cf-routing-release and deploy it to bosh-lite?
(2) I also tried an API call to map an external port on the router to the  app1.bosh-lite.com:61616
```
curl 10.24.0.134:3000/routing/v1/tcp_routes/create -X POST -d '[{"route":{"router_group_guid": "tcp-default", "port": 61616}, "backend_ip": "app1.bosh-lite.com", "backend_port": 61616}]'
```
But got the following error:
```
curl: (52) Empty reply from server
```
The result of command `bosh vms` is as below:
```
Deployment `cf-warden'

Director task 30

Task 30 done

+------------------------------------+---------+---------------+--------------+
| Job/index                          | State   | Resource Pool | IPs          |
+------------------------------------+---------+---------------+--------------+
| api_z1/0                           | running | large_z1      | 10.244.0.134 |
| consul_z1/0                        | running | small_z1      | 10.244.0.54  |
| doppler_z1/0                       | running | medium_z1     | 10.244.0.142 |
| etcd_z1/0                          | running | medium_z1     | 10.244.0.42  |
| ha_proxy_z1/0                      | running | router_z1     | 10.244.0.34  |
| hm9000_z1/0                        | running | medium_z1     | 10.244.0.138 |
| loggregator_trafficcontroller_z1/0 | running | small_z1      | 10.244.0.146 |
| nats_z1/0                          | running | medium_z1     | 10.244.0.6   |
| postgres_z1/0                      | running | medium_z1     | 10.244.0.30  |
| router_z1/0                        | running | router_z1     | 10.244.0.22  |
| runner_z1/0                        | running | runner_z1     | 10.244.0.26  |
| uaa_z1/0                           | running | medium_z1     | 10.244.0.130 |
+------------------------------------+---------+---------------+--------------+

VMs total: 12
Deployment `cf-warden-diego'

Director task 31

Task 31 done

+--------------------+---------+------------------+---------------+
| Job/index          | State   | Resource Pool    | IPs           |
+--------------------+---------+------------------+---------------+
| access_z1/0        | running | access_z1        | 10.244.16.6   |
| brain_z1/0         | running | brain_z1         | 10.244.16.134 |
| cc_bridge_z1/0     | running | cc_bridge_z1     | 10.244.16.142 |
| cell_z1/0          | running | cell_z1          | 10.244.16.138 |
| database_z1/0      | running | database_z1      | 10.244.16.130 |
| route_emitter_z1/0 | running | route_emitter_z1 | 10.244.16.146 |
+--------------------+---------+------------------+---------------+

VMs total: 6
Deployment `cf-warden-routing'

Director task 32

Task 32 done

+-----------------+---------+---------------+------------+
| Job/index       | State   | Resource Pool | IPs        |
+-----------------+---------+---------------+------------+
| tcp_router_z1/0 | running | tcp_router_z1 | 10.244.8.2 |
+-----------------+---------+---------------+------------+

```

**Comment by shalako** [comment]
Hello @samdai,

TCP routing is not yet supported in Cloud Foundry. It is currently in development and we still have some ways to go. 

More specifically, Cloud Foundry does not currently support applications on Diego listening on any port besides 8080. When CF tells Diego to run an app, it must tell Diego what port to open on the container; this is currently hardcoded to 8080. We are currently enhancing this behavior to allow you to specify the ports an app will listen on.

Also, you cannot currently use CF to configure the TCP router. We are currently working on this as well.

If you are curious and want to play around, there are a couple of ways you can make a TCP request to an app on Diego. These are not recommended workarounds; these are ways to test functionality that is still in development using internal interfaces. 

If your app listens on 8080 then you can push it with CF, then use Routing API to register a route with the ip and port of the Cell host where the app is running.

1. push your app normally (it must be listening on 8080)
2. curl the api to get the host ip and port provided by Diego for the app instance
  
```
$ cf app myapp --guid
21305e9e-2263-4442-a8ad-de4ef1f99bbf

$ cf curl /v2/apps/21305e9e-2263-4442-a8ad-de4ef1f99bbf/stats
 {
   "0": {
      "state": "RUNNING",
      "stats": {
         "name": "myapp",
         "uris": [
            "myapp.bosh-lite.com"
         ],
         "host": "10.244.0.26",
         "port": 61001,
         "uptime": 112225,
         "mem_quota": 268435456,
         "disk_quota": 1073741824,
         "fds_quota": 16384,
         "usage": {
            "time": "2015-12-16 02:14:59 +0000",
            "cpu": 0.00032506092163534384,
            "mem": 155209728,
            "disk": 0
         }
      }
   }
}
 ```

3. curl the routing api for the guid of the router_group_guid

```
$ cf curl /routing/v1/router_groups
[
   {
      "guid": "bad25cff-9332-48a6-8603-b619858e7992",
      "name": "default-tcp",
      "type": "tcp"
   }
]
```

4. create a tcp route for port 61616 using the routing api: 

```
$ curl api.bosh-lite.com/routing/v1/tcp_routes/create -X POST -d '[{"route":{"router_group_guid": "bad25cff-9332-48a6-8603-b619858e7992", "port": 61616}, "backend_ip": "10.244.0.26", "backend_port": 61001}]'
```

5. Now you should be able to access the app with `nc -v 10.244.8.2 61616`


Another way to see TCP routing in action is to use the Veritas CLI for Diego to push a docker image. The benefit here is you can specify the ports that should be opened on the container AND automatically update the routing tier (no need for the curl to the routing API). On the [README for Veritas](https://github.com/pivotal-cf-experimental/veritas/blob/master/README.md), you'll find an example for pushing Redis listening on port 6379, and accessing Redis over TCP running on Diego. For this to work you have to deploy the tcp-emitter with cf-routing-release.

**Comment by samdai** [comment]
Hello @shalako,
Thanks your answer,  now I meet one  new issue, when I  follow your work-around method, when I create tcp router using the following api:
```
curl api.bosh-lite.com/routing/v1/tcp_routes/create -X POST -d '[{"route":{"router_group_guid": "bad25cff-9332-48a6-8603-b619858e7992", "port": 61616}, "backend_ip": "10.244.16.138", "backend_port": 60112}]'
```
got the following error:

```
{"name":"UnauthorizedError","message":"Invalid token format"}
```

**Comment by shalako** [comment]
Hello, Routing API requires token for auth by default. For more info, see https://github.com/cloudfoundry-incubator/routing-api/blob/master/README.md.

Auth can be disabled using manifest property `routing-api.auth_disabled`. See https://github.com/cloudfoundry-incubator/cf-routing-release/blob/develop/jobs/routing-api/spec#L19
