### ISSUE TITLE
Docs refer to a non-existent directory: cf/cf-release/bosh-lite/deployments

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry-incubator/cf-routing-release#19]
Probably something obvious is missing between steps 4 and 5 of https://github.com/cloudfoundry-incubator/cf-routing-release/blob/develop/README.md:

```
4. Install spiff, a tool for generating BOSH manifests. spiff is required for running the scripts in later 
steps. Stable binaries can be downloaded from Spiff Releases.
...
5. Generate and target router's manifest:

cd ~/workspace/cf-routing-release
./scripts/generate-bosh-lite-manifest

It expects cf.yml to be present in ~/workspace/cf-release/bosh-lite/deployments... 
```

Except there is no `deployments` directory in `cf-release/bosh-lite`, just  a directory called `stubs`. I don't see a `cf.yml` in any of the cf directories I've downloaded.  Should I be using `spiff` to generate the `yaml` files for `./scripts/generate-bosh-lite-manifest` ?

**Comment by ericpromislow** [comment]
Clue #1: `cf-release/.gitignore` includes `bosh-lite/deployments/*` - so this worked on someone's machine.

**Comment by ericpromislow** [comment]
`cloudfoundry-incubator/diego-release/.gitignore` includes `bosh-lite`

**Comment by fordaz** [comment]
What seems to be missing are the instructions #6 and #7 as described in the [Diego Release](https://github.com/cloudfoundry-incubator/diego-release) which will generate the corresponding deployment manifest in the expected directory by default.

I think the readme can be improved by not only saying that it expects the cf.yml and diego.yml to be present, but to give more details about how to generate them.

@ericpromislow thanks for your feedback, we'll update the readme !

**Comment by ericpromislow** [comment]
ok. I jumped right into learning about this repo without actually doing a cf-release & diego-release. The use of ~/workspace is documented in diego-release/docs, and I see how to do the manifests. I can add a quick note to the readme for anyone else who happens to jump into this repo first.

**Comment by ericpromislow** [comment]
Updated README.md in https://github.com/cloudfoundry-incubator/cf-routing-release/pull/21
