### ISSUE TITLE
cf router-groups can't work

### ISSUE THREAD

**Issue by samdai** [cloudfoundry-incubator/cf-routing-release#28]
I just deployed cf-routing-release version 0.126.0 to bosh-lite according to the steps in README.md, but meet an issue, when I run command "cf router-groups", the following error is shown: 
`FAILED This command requires the Routing API. Your targeted endpoint reports it is not enabled. ` 

But I have enabled routing_api by setting "routing_api: enabled: true" in cf.yml. what else do I need configure?

CF release version: v235
Diego version: v0.1467.0

**Comment by markstgodard** [comment]
@samdai What do you see if you curl the info endpoint?

```
cf curl /v2/info
```

Do you see a **routing_endpoint** ?

If you have the routing api enabled properly, it will show up in v2/info.

**Comment by markstgodard** [comment]
Also just to confirm, you added something like this to your CF deployment manifest, properties section:

```yml
  routing_api:
    enabled: true
```

**Comment by samdai** [comment]
When I curl the info endpoint "cf curl /v2/info", I can see the routing_endpoint, the value is "https://api.bosh-lite.com/routing", and I have added the following settings in CF deployment manifest:
```
routing_api:
     enabled: true
default_to_diego_backend: true
```

**Comment by markstgodard** [comment]
@samdai cf cli caches `RoutingEndpoint` in `~/cf/config.json` so do a cf login again
```
cf login
```

and that should fix it.

Let me know

**Comment by markstgodard** [comment]
@samdai if that fixes it for you,  I'll update the README so no one else gets tripped up on that.

Cheers

**Comment by samdai** [comment]
Yes, your fixes works, thank you very much.

Sam
