### ISSUE TITLE
Two questions about tcp router

### ISSUE THREAD

**Issue by samdai** [cloudfoundry-incubator/cf-routing-release#29]
Hello, 
I have the following questions for tcp router, please help to answer:
(1)When I execute command "cf push app1 --no-start -d tcp.bosh-lite.com --random-route, there is the following error, what do I need configure for this?
```
Creating random route for tcp.bosh-lite.com...
FAILED
Server error, status code: 400, error code: 310009, message: You have exceeded the total reserved route ports for your organization's quota.
```
(2) I only see the command to create a shared-domain for the TCP router group, is there a way to update an existing share-domain(for example bosh-lite.com) for the TCP router group?

**Comment by markstgodard** [comment]
1.) We are currently implementing TCP route quotas,  so by default its not enabled.
Also the CF CLI has not been updated yet to update total reserved route ports

To get past his you can use `cf curl` to either update the default org quota or create a new org quota:

For example, updating the default quota:

Find the guid for the default quota definition:
```
cf curl /v2/quota_definitions?q=name:default 
{
   "total_results": 1,
   "total_pages": 1,
   "prev_url": null,
   "next_url": null,
   "resources": [
      {
         "metadata": {
            "guid": "a692fc6f-9b4b-4b3c-a60e-c82bfa880f26",
            "url": "/v2/quota_definitions/a692fc6f-9b4b-4b3c-a60e-c82bfa880f26",
            "created_at": "2016-04-13T16:09:29Z",
            "updated_at": null
         },
         "entity": {
            "name": "default",
            "non_basic_services_allowed": true,
            "total_services": 100,
            "total_routes": 1000,
            "total_private_domains": -1,
            "memory_limit": 10240,
            "trial_db_allowed": false,
            "instance_memory_limit": -1,
            "app_instance_limit": -1,
            "app_task_limit": -1,
            "total_service_keys": 1000,
            "total_reserved_route_ports": 0
         }
      }
   ]
}
```
Note the `url`for quota_definition and use to update by guid to update the total reserved route ports  (i.e. 25)

```
cf curl /v2/quota_definitions/a692fc6f-9b4b-4b3c-a60e-c82bfa880f26 -X PUT -d '{"total_reserved_route_ports": 25}'
```

Your guid will be different, but this will allow you to update it until the CF CLI has been updated for updating total reserved route ports in quotas.

2.) Right now we do not allow update

Cheers

**Comment by samdai** [comment]
Thanks, TCP route quotas issue is resolved using your method. Now there is a new issue, my java application start a SMTP server to listen to tcp port 25000, I deployed this app to diego and mapped this app to route tcp.bosh-lite.com:25000 using the following commands:
```
cf push app1 --no-start 
cf enable-diego app1
cf start app1
cf map-route app1 tcp.bosh-lite.com --port 25000
```
but when I execute the command `curl tcp.bosh-lite.com:25000`, return the following message:
`curl: (52) Empty reply from server`
and if I execute command `telnet tcp.bosh-lite.com 25000`, return the following message:
```
Trying 10.244.0.34...
telnet: connect to address 10.244.0.34: Connection refused
telnet: Unable to connect to remote host

```
Is the tcp port 25000 in the route same as the tcp port 25000 exposed in app container?  or it maps to another internal tcp port in app container?

Thanks,
Sam

**Comment by markstgodard** [comment]
1.) You need to use `-d` in `cf push` to specify this app is associated with the tcp domain.
Also I believe right now cf cli only supports setting a random port (i.e. --random-port)
So I think right now you can do something like this:

- Push the app with no route and using tcp domain

```
cf push app1 -d tcp.bosh-lite.com --no-start --no-route
```

- update the app's ports. This does not map the port, but just updates the app info about what ports it may use. Also as discussed, the cf cli should be being updated to be able to specific this from cli soon.

```
cf curl -X PUT /v2/apps/`cf app hello --guid` -d '{"ports": [25000]}
```

If you then run this command you will see the ports the app supports:

```
cf curl /v2/apps/`cf app app1 --guid`
```

You should the ports has an array of one, and the value 25000

```json

      "ports": [
         25000
      ],

```


- map the route

```
cf map-route app1 tcp.bosh-lite.com --port 25000
```

**Comment by samdai** [comment]
Firstly thanks your response. I tried your method, but still can't work, my application is a jetty application, when application is started, also start a SMTP server to listen to tcp port 25000. I execute the following commands to start my application:
```
cf push app1 -d tcp.bosh-lite.com --no-start --no-route
cf curl -X PUT /v2/apps/`cf app app1 --guid` -d '{"ports": [8080,25000]}
cf map-route app1 tcp.bosh-lite.com --port 25000
cf map-route app1 bosh-lite.com --hostname app1
cf enable-diego app1
cf start app1
```
but application can't be started, the following is the error message:
Timed out after 1m0s: health check never passed.
```
2016-05-02T00:35:24.35+0800 [CELL/0]     OUT Exit status 0
2016-05-02T00:35:24.55+0800 [APP/0]      OUT Exit status 255
2016-05-02T00:35:24.57+0800 [API/0]      OUT App instance exited with guid 955a6710-e533-4b13-b802-7e27f45f65d4 payload: {"instance"=>"28e97ac4-7e01-4c42-5dec-6ab657c7f515", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 1 error(s) occurred:\n\n* Exited with status 1\n* 2 error(s) occurred:\n\n* cancelled\n* cancelled", "crash_count"=>3, "crash_timestamp"=>1462120524555528192, "version"=>"8c7df676-86c2-4b68-8789-1f867a8de83a"
```
Then I execute the commands 
```
cf set-health-check app1 none
cf restart app1
```
app1 can be started, but when I execute command `telnet tcp.bosh-lite.com 25000`, return the same error message as last time:

```
Trying 10.244.0.34...
telnet: connect to address 10.244.0.34: Connection refused
telnet: Unable to connect to remote host

```

**Comment by markstgodard** [comment]
Hi @samdai 

It looks like tcp.bosh-lite.com is resolving to the load balancer (ha_proxy_z1) in CF. So basically its trying to connect to the wrong haproxy on (10.244.0.34)

```
Deployment `cf-warden'

+------------------------------------+---------+-----------+--------------+
| VM                                 | State   | VM Type   | IPs          |
+------------------------------------+---------+-----------+--------------+
| api_z1/0                           | running | large_z1  | 10.244.0.138 |
| blobstore_z1/0                     | running | medium_z1 | 10.244.0.130 |
| consul_z1/0                        | running | small_z1  | 10.244.0.54  |
| doppler_z1/0                       | running | medium_z1 | 10.244.0.146 |
| etcd_z1/0                          | running | medium_z1 | 10.244.0.42  |
| ha_proxy_z1/0                      | running | router_z1 | 10.244.0.34  |
| hm9000_z1/0                        | running | medium_z1 | 10.244.0.142 |
| loggregator_trafficcontroller_z1/0 | running | small_z1  | 10.244.0.150 |
| nats_z1/0                          | running | medium_z1 | 10.244.0.6   |
| postgres_z1/0                      | running | medium_z1 | 10.244.0.30  |
| router_z1/0                        | running | router_z1 | 10.244.0.22  |
| runner_z1/0                        | running | runner_z1 | 10.244.0.26  |
| uaa_z1/0                           | running | medium_z1 | 10.244.0.134 |
+------------------------------------+---------+-----------+--------------+

```

we want it to connect to the tcp_router_z1 in the routing deployment:  10.244.14.2 

```
deployment 'cf-warden-routing' 

+------------------+---------+----------------+--------------+
| VM               | State   | VM Type        | IPs          |
+------------------+---------+----------------+--------------+
| routing_api_z1/0 | running | routing_api_z1 | 10.244.14.10 |
| tcp_emitter_z1/0 | running | tcp_emitter_z1 | 10.244.14.6  |
| tcp_router_z1/0  | running | tcp_router_z1  | 10.244.14.2  |
+------------------+---------+----------------+--------------+
```


Typically for tcp routing and DNS, for example when deploying to AWS, we would need to setup an ELB and routing to make sure that the TCP domain resolves to the proper Load balancer (and not our CF one that routes gorouter)

For bosh-lite,  you can add an entry to /etc/hosts

```
10.244.14.2 tcp.bosh-lite.com
```

So locally on bosh-lite, its a bit of a workaround, but its a DNS issue for this case.

You could also try and telnet to that IP and port 25000 to see if its listening.

Cheers

**Comment by samdai** [comment]
I just tried it, I added the following entry to /etc/hosts
`10.244.14.2 tcp.bosh-lite.com`
but still have issues:
(1) If don't execute command `cf set-health-check app1 none`, application can't be started, the following is the error message:
`Timed out after 1m0s: health check never passed.`
(2) if execute command `cf set-health-check app1 none`, application can be started, when I execute the command `telnet tcp.bosh-lite.com 25000`, will show the following message:

```
Trying 10.244.14.2...
Connected to tcp.bosh-lite.com.
Escape character is '^]'.
Connection closed by foreign host
```

But the content is not what I expected, in my local machine, if I start my application in eclipse, not CF container, when I execute the command `telnet tcp.bosh-lite.com 25000`, will show the following message, so I suspect the exposed tcp port 25000 is not mapped to internal tcp port 25000 of app container.


```
Trying ::1...
Connected to localhost.
Escape character is '^]'.
220 211.98.70.226 ESMTP SubEthaSMTP 3.1.7
```

**Comment by samdai** [comment]
Got it, thanks, I will try custom app ports when this feature is ready.

**Comment by shalako** [comment]
> my java application start a SMTP server to listen to tcp port 25000

@samdai Are you able to configure your SMTP service to listen on port 8080, or is this being used by another process in the container?

**Comment by samdai** [comment]
Yes, port 8080 is used by Jetty server in the container for my application, so this port can't be listened by SMTP server.

**Comment by GunSik2** [comment]
For anyone who encounters the same problem in bosh-lite, I suggest to add iptables in bosh-lite vm.
By default bosh-lite only added 80, 443 to haproxy(10.244.0.34). To test tcp routing, you need to add those port to map to tcp-router(10.244.14.2). 
Sample command to add 1081 port to tcp-router: 
sudo iptables -A FORWARD -p tcp -d 10.244.14.2 --dport 1081 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
sudo iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 1081 -j DNAT --to-destination 10.244.14.2:1081
